#!/usr/bin/env node
// Bundle review/data/batches/*.json into review/data/batches.js (a classic script that sets
// window.PUZZLE_DATA) so the review app needs no fetch() and works from any static host.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "review", "data", "batches"), OUT = join(ROOT, "review", "data", "batches.js");
const batches = readdirSync(SRC).filter((f) => f.endsWith(".json")).sort().map((f) => JSON.parse(readFileSync(join(SRC, f), "utf8")));
writeFileSync(OUT, "// Generated by cli/pack.mjs. Do not edit by hand.\nwindow.PUZZLE_DATA = " + JSON.stringify({ batches }) + ";\n");
console.log(`packed ${batches.length} batches, ${batches.reduce((s, b) => s + b.puzzles.length, 0)} puzzles -> review/data/batches.js`);
