"""Bundle every batch in review/data/batches/*.json into review/data/batches.js.

The review app loads data through a <script> tag rather than fetch() so it works
from GitHub Pages, from a local file:// double-click, and inside sandboxed viewers.
Run after generating or editing a batch:  python tools/pack_review_data.py
"""
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "review", "data", "batches")
OUT = os.path.join(ROOT, "review", "data", "batches.js")

batches = []
for path in sorted(glob.glob(os.path.join(SRC, "*.json"))):
    with open(path) as f:
        batches.append(json.load(f))

with open(OUT, "w") as f:
    f.write("// Generated by tools/pack_review_data.py. Do not edit by hand.\n")
    f.write("window.PUZZLE_DATA = ")
    json.dump({"batches": batches}, f, separators=(",", ":"))
    f.write(";\n")

n = sum(len(b["puzzles"]) for b in batches)
print(f"packed {len(batches)} batches, {n} puzzles -> {os.path.relpath(OUT, ROOT)}")
